/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author ADMIN
 */
public class ChatComponent extends javax.swing.JPanel {

    /**
     * Creates new form ChatComponent
     */
    public ChatComponent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        scrollComponent = new javax.swing.JScrollPane();
        scrollPanel = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        lblChat = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 85));
        setPreferredSize(new java.awt.Dimension(32767, 85));

        scrollComponent.setMaximumSize(new java.awt.Dimension(807, 85));
        scrollComponent.setPreferredSize(new java.awt.Dimension(807, 85));

        scrollPanel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        scrollPanel.setMaximumSize(new java.awt.Dimension(807, 85));
        scrollPanel.setPreferredSize(new java.awt.Dimension(807, 85));

        user.setText("jLabel1");

        lblChat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblChat.setText("jLabel2");

        javax.swing.GroupLayout scrollPanelLayout = new javax.swing.GroupLayout(scrollPanel);
        scrollPanel.setLayout(scrollPanelLayout);
        scrollPanelLayout.setHorizontalGroup(
                scrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(scrollPanelLayout.createSequentialGroup()
                                .addGroup(scrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(scrollPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(user))
                                        .addGroup(scrollPanelLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(lblChat, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(371, Short.MAX_VALUE))
        );
        scrollPanelLayout.setVerticalGroup(
                scrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(scrollPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(user)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblChat)
                                .addContainerGap(37, Short.MAX_VALUE))
        );

        scrollComponent.setViewportView(scrollPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(scrollComponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scrollComponent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>


    // Variables declaration - do not modify
     javax.swing.JLabel lblChat;
     javax.swing.JScrollPane scrollComponent;
     javax.swing.JPanel scrollPanel;
     javax.swing.JLabel user;
    // End of variables declaration
}
