import javax.swing.*;
import java.awt.*;

class Login1 extends javax.swing.JFrame {
    // DataBase dataBase;
    JFrame loginFrame = this;
    /*  private javax.swing.JTextField nameField;
      private javax.swing.JPasswordField passwordField1;
      private javax.swing.JPasswordField passwordField2;
      private javax.swing.JLabel passwordLabel1;
      private javax.swing.JLabel passwordLabel2;
      private javax.swing.JButton signInBt;
      private javax.swing.JTabbedPane signInPane;
      private javax.swing.JPanel signInPanel;
      private javax.swing.JButton signUpBt;
      private javax.swing.JPanel signUpPanel;
      private javax.swing.JTextField userIdField1;
      private javax.swing.JTextField userIdField2;
      private javax.swing.JLabel userIdLabel1;
      private javax.swing.JLabel userIdLabel2;*/
    public void Login1() {
        // dataBase = new DataBase();
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        image = new javax.swing.JLabel();
        signInPane = new javax.swing.JTabbedPane();
        signInPanel = new javax.swing.JPanel();
        userIdLabel2 = new javax.swing.JLabel();
        userIdField2 = new javax.swing.JTextField();
        passwordLabel2 = new javax.swing.JLabel();
        passwordField2 = new javax.swing.JPasswordField();
        signInBt = new javax.swing.JButton();
        signUpPanel = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        userIdLabel1 = new javax.swing.JLabel();
        userIdField1 = new javax.swing.JTextField();
        passwordField1 = new javax.swing.JPasswordField();
        signUpBt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("LOGIN.png"))); // NOI18N
        image.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), null));

        userIdLabel2.setText("User Id");

        userIdField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        passwordLabel2.setText("Password");

        passwordField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        signInBt.setText("Sign In");

        javax.swing.GroupLayout signInPanelLayout = new javax.swing.GroupLayout(signInPanel);
        signInPanel.setLayout(signInPanelLayout);
        signInPanelLayout.setHorizontalGroup(
                signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(signInPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(userIdLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                                .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(passwordField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(userIdField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51))
                        .addGroup(signInPanelLayout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(signInBt)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signInPanelLayout.setVerticalGroup(
                signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(signInPanelLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(userIdLabel2)
                                        .addComponent(userIdField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordLabel2)
                                        .addComponent(passwordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addComponent(signInBt)
                                .addContainerGap(71, Short.MAX_VALUE))
        );

        signInPane.addTab("Sign In", signInPanel);

        nameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        name.setText("Name");

        passwordLabel1.setText("Password");

        userIdLabel1.setText("UserId");

        userIdField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        passwordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        signUpBt.setText("Sign Up");

        javax.swing.GroupLayout signUpPanelLayout = new javax.swing.GroupLayout(signUpPanel);
        signUpPanel.setLayout(signUpPanelLayout);
        signUpPanelLayout.setHorizontalGroup(
                signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(userIdLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(signUpPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(userIdField1)
                                                        .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                                        .addGroup(signUpPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                                .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(52, 52, 52))
                        .addGroup(signUpPanelLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(signUpBt)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signUpPanelLayout.setVerticalGroup(
                signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(signUpPanelLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(name))
                                .addGap(29, 29, 29)
                                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(userIdLabel1)
                                        .addComponent(userIdField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordLabel1)
                                        .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addComponent(signUpBt)
                                .addContainerGap(52, Short.MAX_VALUE))
        );

        signInPane.addTab("Sign Up", signUpPanel);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("chatlogo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(signInPane, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(89, 89, 89)
                                                .addComponent(signInPane, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(154, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(139, 139, 139))
        );

        pack();
        setVisible(true);
    }// </editor-fold>

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    public void signUp()
    {
        String username = nameField.getText();
        String userid = userIdField1.getText();
        String password = new String(passwordField1.getPassword());

        try {
            if(username.isEmpty() && userid.isEmpty() && password.isEmpty() )
            {
                JOptionPane.showMessageDialog(null,"Do check...All the inputs are empty");
            }
            else if (username.isEmpty() || userid.isEmpty() ||password.isEmpty() ) {
                //throw new IllegalArgumentException("Username cannot be empty");
                JOptionPane.showMessageDialog(null,"Enter the missing fields");
            }
            else {
                // dataBase.insertSignupDetails(username,userid,password);
                JOptionPane.showMessageDialog(null,"Sign is done successfully");
//                dataBase.flush();
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(Login1.this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }/* catch (Exception e) {
            JOptionPane.showMessageDialog(Login.this,e.getMessage());
        }*/

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        new Login1();
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JPasswordField passwordField2;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JLabel passwordLabel2;
    private javax.swing.JButton signInBt;
    private javax.swing.JTabbedPane signInPane;
    private javax.swing.JPanel signInPanel;
    private javax.swing.JButton signUpBt;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JTextField userIdField1;
    private javax.swing.JTextField userIdField2;
    private javax.swing.JLabel userIdLabel1;
    private javax.swing.JLabel userIdLabel2;
    // End of variables declaration
}